// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ecomm

import (
	"context"
)

type Querier interface {
	GetProductByID(ctx context.Context, id int64) (Product, error)
	GetProducts(ctx context.Context) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
